spring:
  application:
    name: tiered-membership-system

  datasource:
    url: jdbc:postgresql://localhost:5432/membership_manager
    username: admin
    password: admin

  jpa:
    hibernate:
      ddl-auto: validate
      open-in-view: false

    properties:
      hibernate:
        format_sql: true

    show-sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true

server:
  port: 8080